import './globals.css'
import style from './layout.module.css'
import type { Metadata } from 'next'
import Header from './(header)/Header'
import { Inter } from 'next/font/google'
import Footer from './(footer)/Footer'
import CopyRight from './(footer)/CopyRight'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className={style.inter_className}>
          {children}
          <Footer />
          <CopyRight />
        </div>
      </body>
    </html>
  )
}
